name: Build and Deploy

on: [push, pull_request]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull git repo
        uses: actions/checkout@v4

      - name: Start services with Docker Compose
        run: |
          docker compose -f docker-compose-dev.yml up -d
          echo "Waiting for app to start..."
          sleep 20  # Give the app and database some time to be ready
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: 'http://localhost:8000'